name         'vladgh-mysql'
version      '0.1.0'
author       'Vlad Ghinea'
license      'Apache 2.0'
summary      'Manages MySQL.'
description  'Manages MySQL.'
source       'https://github.com/vladgh/puppet-module-mysql'
project_page 'https://github.com/vladgh/puppet-module-mysql'

dependency   'puppetlabs-stdlib', '>= 4.0.0'
